services:
  # A web service for the Browser-Use Web UI
  - type: web
    name: browser-use-web-ui
    env: python
    buildCommand: apt-get update buildCommand: pip install -r requirements.txtbuildCommand: pip install -r requirements.txt apt-get install -y wget gnupg ca-certificates buildCommand: pip install -r requirements.txtbuildCommand: pip install -r requirements.txt wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - buildCommand: pip install -r requirements.txtbuildCommand: pip install -r requirements.txt echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list buildCommand: pip install -r requirements.txtbuildCommand: pip install -r requirements.txt apt-get update buildCommand: pip install -r requirements.txtbuildCommand: pip install -r requirements.txt apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 buildCommand: pip install -r requirements.txtbuildCommand: pip install -r requirements.txt pip install -r requirements.txt buildCommand: pip install -r requirements.txtbuildCommand: pip install -r requirements.txt python -m playwright install --with-deps chromium
    startCommand: python webui.py --ip 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
    autoDeploy: true
