services:
  # A web service for the Browser-Use Web UI
  - type: web
    name: browser-use-web-ui
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python webui.py --ip 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
    autoDeploy: true
